### ISSUE TITLE
Question: Is porting this functionality to the Super NT possible

### ISSUE THREAD

**Issue by RealEMK** [RobertPeip/FPGBA#35]
Hi Robert,

Came across this project and was wondering if there's any chance of you porting this to Super NT as it's also on the FPGA architecture. A GBA game just sounds perfect when paired with a modern display and a SNES controller.

-Eric

**Comment by RobertPeip** [comment]
No, it's not possible, as the SuperNT is a closed platform. Even if the developers of the SuperNT would want to take this core, they are not allowed to do it because of the license.

But you can buy a DE-10 Nano for ~120$ and play this GBA core with a SNES controller on the MiSTer platform: https://github.com/MiSTer-devel/GBA_MiSTer
